### PR TITLE
Fix #2

### LINKED ISSUE #2: Remove excess styles
There's a lot of code at the start of this that gives styles for fonts and typography. This is not what i expect out of a simple grid – which should be simply a grid. I recommend removing this and implementing them as another repo (so as to not make this into yet another framework).
- Jeff

### PR DESCRIPTION
**Pull request by abinxzh**
Refer to #2

### CODE REVIEW

**Comment by zachacole** [comment]
@notjefffree Thanks for these suggestions! Re: issue #2 - would you think it valuable to have an option for people to toggle on/off whether or not they want typographic styles included? Part of me feels strongly that web design is largely based around type and grids, hence the inclusion, but I also see your point about keeping a "simple grid" project to just the grid and nothing else. Thanks!

**Comment by abinxzh** [comment]
Definitely @zachacole. I use http://tachyons.io for dev, and would love a simple grid to pop in. It already has my typographical styles in there, so I don't wanna duplicate too much.

**Comment by zachacole** [comment]
@notjefffree Ah, I see. Tachyons is wonderful as well. I think I'll add a file to the download package that contains just the grid and no text styles, per your PR here, but I'll close this PR in order to maintain the base style sheet as well. Thanks!

**Comment by abinxzh** [comment]
Sure, all good 👍

**Pull request closed without merging**
